[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
enumflags2 = "0.7.10"
itertools = "0.13.0"

[profile.release]
debug = true
